version: "3.9"

services:
  app:
    image: shivaraj3652/todo-app-test:latest
    container_name: todo-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SERVERPORT: "8080"
      HOST: "postgres"
      DBUSER: "todo_user"
      PASSWORD: "todo_pass"
      DBNAME: "todo_db"
      PORT: "5432"
      SSL: "disable"
      JWTSECRET: "todo_secret_key"
      REDISHOST: "redis:6379"
    restart: always
    networks:
      - todo-net

  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - todo-net

  redis:
    image: redis:7-alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  pgdata: